[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pysubsea"
version = "0.1.6"
description = "Package for subsea pipelines and risers design in Python"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = "MIT"
authors = [{ name = "Subsea Energies", email = "info@subseaenergies.com" }]
dependencies = []

keywords = ["subsea", "pipeline", "abaqus", "FEM", "python", "engineering"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Documentation = "https://py-subsea.github.io/py-subsea/"
Source = "https://github.com/py-subsea/py-subsea"
Tracker = "https://github.com/py-subsea/py-subsea/issues"

[tool.setuptools.packages.find]
where = ["src"]
